<?php

/**
 * BaseResource
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property enum $status
 * @property integer $parent_id
 * @property string $extension
 * @property long $size
 * @property string $path
 * @property string $icon_path
 * @property string $thumbnail_path
 * @property enum $type
 * @property string $sender
 * @property string $city
 * @property Album $Album
 * 
 * @method integer  getId()             Returns the current record's "id" value
 * @method string   getName()           Returns the current record's "name" value
 * @method string   getDescription()    Returns the current record's "description" value
 * @method enum     getStatus()         Returns the current record's "status" value
 * @method integer  getParentId()       Returns the current record's "parent_id" value
 * @method string   getExtension()      Returns the current record's "extension" value
 * @method long     getSize()           Returns the current record's "size" value
 * @method string   getPath()           Returns the current record's "path" value
 * @method string   getIconPath()       Returns the current record's "icon_path" value
 * @method string   getThumbnailPath()  Returns the current record's "thumbnail_path" value
 * @method enum     getType()           Returns the current record's "type" value
 * @method string   getSender()         Returns the current record's "sender" value
 * @method string   getCity()           Returns the current record's "city" value
 * @method Album    getAlbum()          Returns the current record's "Album" value
 * @method Resource setId()             Sets the current record's "id" value
 * @method Resource setName()           Sets the current record's "name" value
 * @method Resource setDescription()    Sets the current record's "description" value
 * @method Resource setStatus()         Sets the current record's "status" value
 * @method Resource setParentId()       Sets the current record's "parent_id" value
 * @method Resource setExtension()      Sets the current record's "extension" value
 * @method Resource setSize()           Sets the current record's "size" value
 * @method Resource setPath()           Sets the current record's "path" value
 * @method Resource setIconPath()       Sets the current record's "icon_path" value
 * @method Resource setThumbnailPath()  Sets the current record's "thumbnail_path" value
 * @method Resource setType()           Sets the current record's "type" value
 * @method Resource setSender()         Sets the current record's "sender" value
 * @method Resource setCity()           Sets the current record's "city" value
 * @method Resource setAlbum()          Sets the current record's "Album" value
 * 
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseResource extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('resource');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'enabled',
              1 => 'disabled',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('extension', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('size', 'long', null, array(
             'type' => 'long',
             'notnull' => true,
             ));
        $this->hasColumn('path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('icon_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('thumbnail_path', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('type', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'image',
              1 => 'video',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('sender', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('city', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));

        $this->setSubClasses(array(
             'AlbumResource' => 
             array(
              'type' => 'image',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Album', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}