<?php

/**
 * BaseAdvert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property date $start_date
 * @property date $end_date
 * @property string $start_time
 * @property string $end_time
 * @property string $place
 * @property string $province
 * @property enum $type
 * @property string $f_image_path
 * @property string $f_image_name
 * @property string $image_path
 * @property string $image_name
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getDescription()  Returns the current record's "description" value
 * @method date    getStartDate()    Returns the current record's "start_date" value
 * @method date    getEndDate()      Returns the current record's "end_date" value
 * @method string  getStartTime()    Returns the current record's "start_time" value
 * @method string  getEndTime()      Returns the current record's "end_time" value
 * @method string  getPlace()        Returns the current record's "place" value
 * @method string  getProvince()     Returns the current record's "province" value
 * @method enum    getType()         Returns the current record's "type" value
 * @method string  getFImagePath()   Returns the current record's "f_image_path" value
 * @method string  getFImageName()   Returns the current record's "f_image_name" value
 * @method string  getImagePath()    Returns the current record's "image_path" value
 * @method string  getImageName()    Returns the current record's "image_name" value
 * @method Advert  setId()           Sets the current record's "id" value
 * @method Advert  setTitle()        Sets the current record's "title" value
 * @method Advert  setDescription()  Sets the current record's "description" value
 * @method Advert  setStartDate()    Sets the current record's "start_date" value
 * @method Advert  setEndDate()      Sets the current record's "end_date" value
 * @method Advert  setStartTime()    Sets the current record's "start_time" value
 * @method Advert  setEndTime()      Sets the current record's "end_time" value
 * @method Advert  setPlace()        Sets the current record's "place" value
 * @method Advert  setProvince()     Sets the current record's "province" value
 * @method Advert  setType()         Sets the current record's "type" value
 * @method Advert  setFImagePath()   Sets the current record's "f_image_path" value
 * @method Advert  setFImageName()   Sets the current record's "f_image_name" value
 * @method Advert  setImagePath()    Sets the current record's "image_path" value
 * @method Advert  setImageName()    Sets the current record's "image_name" value
 * 
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvert extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advert');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('end_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('start_time', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('end_time', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('place', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('province', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'enum', 11, array(
             'type' => 'enum',
             'length' => 11,
             'values' => 
             array(
              0 => 'advert',
              1 => 'event',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('f_image_path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('f_image_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('image_path', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('image_name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}