# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Output escaping settings
    escaping_strategy:      false
    escaping_method:        ESC_SPECIALCHARS
    enabled_modules: [default, sfGuardAuth,sfCaptchaGD]
    standard_helpers: [Partial, Cache, I18N]
    charset: utf-8
    i18n: true
    default_culture: es_ES
    # Enable the database manager
    use_database:           true
  .actions:
    login_module: sfGuardAuth
    login_action: signin
    