<?php

/**
 * AlbumResourceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumResourceTable extends ResourceTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumResourceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AlbumResource');
    }
}