<?php

/**
 * AlbumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlbumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlbumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Album');
    }
    
    public function getTopFive(){
		$query = Doctrine_Query::create()->
		addFrom("Album a")
		->addOrderBy("created_at DESC")
		->limit(5);
		
		return $query->execute();
	}
	
}