<?php

/**
 * Album
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Album extends BaseAlbum

{
	/**
	 * @return AlbumTable
	 */
	public static function getRepository(){
		return Doctrine::getTable(__CLASS__);
	}
	
	public static function create(AlbumForm $form){
		$album = new Album();
		$album->setName($form->getValue("name"));
		$album->setType($form->getValue("type"));
		$album->save();
		return $album;
	}
	
	public function getPhotos(){
		if($this->getResourcesOfType("image")){
			return $this->getResourcesOfType("image")->getResources();
		}
		return array();
	}
	
	public function getVideos(){
		if($this->getResourcesOfType("video")){
			return $this->getResourcesOfType("video")->getResources();
		}
		return array();
	}
	
	public function getFrontImage(){
		if($this->getResources()->count()==0){
			return "/images/empty.jpeg";
		}else{
			return $this->getResources()->get(0)->getThumbnailPath();
		}
	}
	
	private function getResourcesOfType($type){
		$q= Doctrine_Query::create()
			->addFrom("Album a")
			->innerJoin("a.Resources r")
			->addWhere("a.id=?",array($this->getId()))
			->addWhere("r.status='enabled'",array())
			->addWhere("r.type =?",array($type));
		return $q->execute()->getFirst();
	}
	
	public static function getPager(){
		$q=Doctrine_Query::create()
			->from("Album a");
		$pager=new sfDoctrinePager("Album",6); 
		$pager->setQuery($q);
		return $pager;
	}
	
}
