<?php

/**
 * AlbumResource
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AlbumResource extends BaseAlbumResource

{

	/**
	 *@return AlbumResourceTable
	 */
	public function getRepository(){
		return Doctrine::getTable(__CLASS__);
	}

	/**
	 * @param Advert $parent
	 * @param sfValidatedFile $file
	 * @return Resource
	 */
	public static function createNew(AlbumResourceForm $form,$type){
		$resource= new Resource();
		$resource->setStatus("disabled");
		$resource->setDescription($form->getValue("description"));
		$parent= Album::getRepository()->find($form->getValue("parent_id"));
		$resource->setParentId($parent->getId());
		$resource->setSender($form->getValue("sender"));
		$resource->setCity($form->getValue("city"));
		$file= $form->getValue("path");
		$resource->setExtension($file->getExtension());
		$folder="albums/".str_replace(" ", "",$parent->getName());
		$path= $resource->saveFile($file,$folder);
		if($type=="image"){
			$resource->setType("image");
// 			$resource->createIcon($folder);
// 			$resource->createThumbnail($folder);
		}else{
			$resource->setType("video");
		}
		$resource->save();
		return $resource;
	}

}
