<?php

/**
 * Dojo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Dojo extends BaseDojo
{
	public static $regions= array(
			"Uruguay" => "Uruguay",
			"Brasil" => "Brasil",
			"Chile" => "Chile",
			"Paraguay" => "Paraguay",
			"Capital Federal"=>"Capital Federal",
			"Buenos Aires"=>"Buenos Aires",
			"Catamarca"=>"Catamarca",
			"Chaco"=>"Chaco",
			"Chubut"=>"Chubut",
			"Cordoba"=>"Cordoba",
			"Corrientes"=>"Corrientes",
			"Entre Rios"=>"Entre Rios",
			"Formosa"=>"Formosa",
			"Jujuy"=>"Jujuy",
			"La Pampa"=>"La Pampa",
			"La Rioja"=>"La Rioja",
			"Mendoza"=>"Mendoza",
			"Misiones"=>"Misiones",
			"Neuquen"=>"Neuquen",
			"Rio Negro"=>"Rio Negro",
			"Salta"=>"Salta",
			"San Juan"=>"San Juan",
			"San Luis"=>"San Luis",
			"Santa Cruz"=>"Santa Cruz",
			"Santa Fe"=>"Santa Fe",
			"Santiago del Estero"=>"Santiago del Estero",
			"Tierra del Fuego"=>"Tierra del Fuego",
			"Tucuman"=>"Tucuman"
	);
	/**
	 * @return DojoTable
	*/
	public static function getRepository(){
		return Doctrine::getTable(__CLASS__);
	}

	public static function create(DojoForm  $form){
		$dojo= new Dojo();
		$dojo->setStatus("disabled");
		$dojo->modify($form);
		$dojo->save();
		$dojo->savePhoto($form);
		return $dojo;
	}

	public function modify(DojoForm $data){
		$this->setName($data->getValue("name"));
		$this->setSensei($data->getValue("sensei"));
		$this->setAddress($data->getValue("address"));
		$this->setCity($data->getValue("city"));
		$this->setProvince($data->getValue("province"));
		$this->setPhone($data->getValue("phone"));
		$this->setEmail($data->getValue("email"));
	}


	public function savePhoto($form){
		if($form->getValue("photo")){
			$photoFile= $form->getValue("photo");
			$fileName=$photoFile->generateFileName();
			$imageFullPath=sfConfig::get("app_resource_upload")."dojos/".$this->getId();
			if(!file_exists($imageFullPath)){
				mkdir($imageFullPath,0777);
			}
			$photoFile->save($imageFullPath."/".$fileName);
			$this->setPhoto("/uploads/resources/dojos/".$this->getId()."/".$fileName);
			$this->save();
		}
	}

	public function getFullAddress(){
		$address= str_replace(" ", "+",$this->getAddress());
		$city= str_replace(" ", "+", $this->getCity());
		$province= str_replace(" ", "+", $this->getProvince());
		$fullAddress = "q=+".$address.",+".$city.",+". $province.",+Argentina";
		return $fullAddress;
	}

	public static function getPager($province=false){
		if($province){
			$q= Doctrine_Query::create()
			->addFrom("Dojo d")
			->addWhere("d.province= :province",array("province"=>$province));
		}else{
			$q=Doctrine_Query::create()
			->from("Dojo d");
		}
		$q->addWhere("d.status= :status",array("status"=>"enabled"));
		$q->addOrderBy("d.created_at DESC");
		$pager=new sfDoctrinePager("Dojo",6);
		$pager->setQuery($q);
		return $pager;
	}
}
