<?php

/**
 * NewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('New');
    }
}