<?php

/**
 * Resource
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    aes
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Resource extends BaseResource
{

	protected  static $supportedImages = array(".jpg",".png",".gif");
	protected static $supportedVideos = array(".mpg",".mpeg",".3gp",".mov");


	

/**
	 *@return ResourceTable
	 */
	public function getRepository(){
		return Doctrine::getTable(__CLASS__);
	}
	
	/**
	 * @param sfValidatedFile  $file
	 * @return string fullfilename
	 */
	public function saveFile($file,$folder) {
		if ($file) {
			$filename = $file->getOriginalName();
			$extension= $file->getOriginalExtension();
			$basePath=sfConfig::get("app_resource_upload").$folder;
			if(!file_exists($basePath)){
				mkdir($basePath,0777);
			}
		}
		$this->setSize($file->getSize());
		$file->save($basePath."/".$filename);
		$this->setName(substr($filename, 0,strpos($filename,".")));
		$this->setExtension($extension);
		$this->setPath("/uploads/resources/".$folder."/".$filename);
	}

	public function getFullName(){
		return $this->getName().$this->getExtension();
	}

	public function createIcon($folder){
		$file=sfConfig::get("app_resource_upload").$folder."/".$this->getFullName();
		$icon = new sfImage($file);
		$icon->thumbnail(32, 32);
		$this->saveSmallVersion($icon, "icon",$folder);
		$this->setIconPath("/uploads/resources/".$folder."/".$this->getName()."_icon".$this->getExtension());
	}

	public function createThumbnail($folder){
		$file=sfConfig::get("app_resource_upload").$folder."/".$this->getFullName();
		$small = new sfImage($file);
		$small->thumbnail(150, 125);
		$this->saveSmallVersion($small, "small",$folder);
		$this->setThumbnailPath("/uploads/resources/".$folder."/".$this->getName()."_small".$this->getExtension());
	}

	private function saveSmallVersion(sfImage $image, $size,$folder) {
		$basePath=sfConfig::get("app_resource_upload").$folder;
		$image->saveAs($basePath."/".$this->getName()."_".$size.$this->getExtension());
	}

}
