JKASiteBundle_admin_jka_site_bundle_resource:
    resource: "@JKASiteBundle/Controller/Resource/"
    type:     admingenerator
    prefix:   /admin/resource

JKASiteBundle_admin_jka_site_bundle_Album:
    resource: "@JKASiteBundle/Controller/Album/"
    type:     admingenerator
    prefix:   /admin/album

JKASiteBundle_admin_jka_site_bundle_dojo:
    resource: "@JKASiteBundle/Controller/Dojo/"
    type:     admingenerator
    prefix:   /admin/dojo

JKASiteBundle_admin_jka_site_bundle_entry:
    resource: "@JKASiteBundle/Controller/Entry/"
    type:     admingenerator
    prefix:   /admin/entry

jka_site:
    resource: "@JKASiteBundle/Resources/config/routing.xml"
    prefix:   /
