<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addresource extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('resource', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'length' => 11,
              'values' => 
              array(
              0 => 'enabled',
              1 => 'disabled',
              ),
              'notnull' => true,
             ),
             'parent_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'extension' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'size' => 
             array(
              'type' => 'long',
              'notnull' => true,
              'length' => NULL,
             ),
             'path' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'icon_path' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'thumbnail_path' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'length' => 11,
              'values' => 
              array(
              0 => 'image',
              1 => 'video',
              ),
              'notnull' => true,
             ),
             'sender' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('resource');
    }
}