<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Adddojo extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('dojo', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'province' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'city' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'address' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'length' => 11,
              'values' => 
              array(
              0 => 'enabled',
              1 => 'disabled',
              ),
              'notnull' => true,
             ),
             'email' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'sensei' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'photo' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('dojo');
    }
}