<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addalbum extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('album', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'length' => 11,
              'values' => 
              array(
              0 => 'public',
              1 => 'private',
              ),
              'notnull' => true,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('album');
    }
}