<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addadvert extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('advert', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 8,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'description' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'start_date' => 
             array(
              'type' => 'date',
              'notnull' => false,
              'length' => 25,
             ),
             'end_date' => 
             array(
              'type' => 'date',
              'notnull' => false,
              'length' => 25,
             ),
             'start_time' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'end_time' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'place' => 
             array(
              'type' => 'string',
              'notnull' => false,
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'length' => 11,
              'values' => 
              array(
              0 => 'advert',
              1 => 'event',
              ),
              'notnull' => true,
             ),
             'f_image_path' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'f_image_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'image_path' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'image_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('advert');
    }
}