generator: admingenerator.generator.doctrine
params:
    model: JKA\SiteBundle\Entity\Dojo
    namespace_prefix: JKA
    concurrency_lock: ~
    bundle_name: SiteBundle
    pk_requirement: ~
    fields:
        image:
          label: Imagen
          dbType: string
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: Dojos
            display: [name,sensei,city,country]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: Nuevo Dojo
            display: [name, sensei,address,city,country,mail,enabled,position,image]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editando \"%object%\"|{ %object%: Dojo.name }|"
            display: [name, sensei,address,city,country,mail,enabled,position,image]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Dojo.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
